fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "null@null.fr" #"%mailer_user%"
        sender_name: "null@null.fr" #"%mailer_user%"