fos_rest:
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'

    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations

    view:
        formats: { json: true, xml: false, rss: false }
        mime_types:
            json: ['application/json', 'application/json;version=1.0']
    serializer:
        serialize_null: true